# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 62502d93eb88488b19fb714d3f823b80b488f771c8a11cc40834be437241abcbf89ce0230fbd339378104a3bf6c06ecee9cae1c95db39d4faaac0d5788c3d3ef

test:
  secret_key_base: 2950b7cb9882f3bf72a1ac2eb5a2a956290096cc038892648ef2cb75e0433ffe609daff0f9573ce21d4fce5ce9a2ff351e18c79cc213693792975a8f0fafdcf9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
